# fly.toml app configuration file generated for backend-floral-log-939 on 2025-09-24T10:42:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-floral-log-939'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  interval = "30s"
  timeout = "10s"
  grace_period = "40s"
  method = "GET"
  path = "/health"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  APP_ENV = "production"
  DEBUG = "False"
